# Generated by Django 5.1.7 on 2025-03-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
