# Generated by Django 5.1.7 on 2025-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_tag_f_name_tag_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
